apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/Starktastic-Homelab/platform.git
    targetRevision: HEAD
    path: apps/services/media/common/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

