extends: default

rules:
  line-length: disable

  document-start: disable

  truthy: disable

  indentation:
    spaces: 2
    indent-sequences: consistent

  comments:
    min-spaces-from-content: 1

  empty-values: disable

ignore: |
  apps/bootstrap/appsets/
  **/templates/
  .git/
