apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.1.14
    helm:
      values: |
        global:
          storageClass: "nfs-pv"
        auth:
          existingSecret: postgres-admin-secret
          secretKeys:
            adminPasswordKey: postgres-password
        primary:
          persistence:
            enabled: true
            storageClass: "nfs-pv"
            size: 8Gi
          podSecurityContext:
            fsGroup: 1001
            enabled: true
          containerSecurityContext:
            runAsUser: 1001
            enabled: true
        volumePermissions:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
