apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.10.2
    helm:
      values: |
        postgresql:
          enabled: false
        redis:
          enabled: false
        authentik:
          log_level: info
          postgresql:
            host: "postgres-postgresql.databases.svc.cluster.local"
            name: "authentik"
            user: "authentik"
            port: 5432
          redis:
            host: "redis-redis.databases.svc.cluster.local"
            port: 6379
        email:
          host: "smtp.eu.mailgun.org"
          port: 587
          username: "postmaster@benplus.vip"
          use_tls: true
          use_ssl: false
          timeout: 10
          from: "noreply@benplus.vip"
        server:
          env:
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-authentik-secret
                  key: password
            - name: AUTHENTIK_RATELIMIT__GLOBAL__PER_IP
              value: "1000/s"
            - name: AUTHENTIK_RATELIMIT__ERROR__PER_IP
              value: "50/s"
            - name: AUTHENTIK_AUTHENTICATION__RATE_LIMIT__LOGIN__LIMIT
              value: "10/m"
          envFrom:
            - secretRef:
                name: authentik-secret
        worker:
          env:
            - name: AUTHENTIK_EMAIL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-authentik-secret
                  key: password
          envFrom:
            - secretRef:
                name: authentik-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
