apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.0
      helm:
        values: |
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: lscr.io/linuxserver/qbittorrent
                    digest: sha256:e0cedcadd62f809efdeddfd32e4d1192f9a74e6e64ed6753bfc6e2c3ed4a714a
                  env:
                    TZ: "Asia/Jerusalem"
                    PUID: "1000"
                    PGID: "1000"
                    WEBUI_PORT: "8080"
                    DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent"
          service:
            main:
              controller: main
              ports:
                http:
                  port: 8080
            bittorrent:
              controller: main
              type: LoadBalancer
              annotations:
                kube-vip.io/loadbalancerIPs: "10.9.8.91"
              ports:
                bittorrent-tcp:
                  enabled: true
                  port: 6881
                  protocol: TCP
                bittorrent-udp:
                  enabled: true
                  port: 6881
                  protocol: UDP
          persistence:
            media:
              enabled: true
              existingClaim: media-library-pvc
              globalMounts:
                - path: /data
            config:
              enabled: true
              type: persistentVolumeClaim
              storageClass: "nfs-pv"
              size: 1Gi
              accessMode: ReadWriteMany
              globalMounts:
                - path: /config
    - repoURL: https://github.com/Starktastic-Homelab/platform.git
      targetRevision: HEAD
      path: apps/services/media/qbittorrent/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

