apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClassReplicaCount: 2
          reclaimPolicy: Retain
        defaultSettings:
          defaultDataPath: /var/lib/longhorn
          createDefaultDiskLabeledNodes: true
          systemManagedComponentsNodeSelector: "node-role.kubernetes.io/worker:true"
        ingress:
          ingressClassName: traefik
          host: longhorn.mgmt.arpa
          tls: false
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
