apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.6.0
      helm:
        values: |
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: lscr.io/linuxserver/prowlarr
                    digest: sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c
                  env:
                    TZ: "Asia/Jerusalem"
                    PUID: "1000"
                    PGID: "1000"
          service:
            main:
              controller: main
              ports:
                http:
                  port: 9696
          persistence:
            config:
              enabled: true
              type: persistentVolumeClaim
              storageClass: "nfs-pv"
              size: 1Gi
              accessMode: ReadWriteMany
              globalMounts:
                - path: /config
    - repoURL: https://github.com/Starktastic-Homelab/platform.git
      targetRevision: HEAD
      path: apps/services/media/prowlarr/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

